### PR TITLE
fix: custom service usage

### LINKED ISSUE #1695: Custom services do not work anymore
**Describe the bug**
I have two gitlab instances configured but during creation of a pull request or opening a commit I will be redirected to gitlab.com instead of the configured instance.

**To Reproduce**
1. configure a custom pull request url:
```
services:
  '<gitDomain>': '<provider>:<webDomain>'
```
2. Try to open a pull request
3. See error

**Expected behavior**
I should be redirected to the configured instance.

**Desktop (please complete the following information):**
 - OS: Windows/Linux/macOS
 - Lazygit Version 0.32.2

**Last working version**
0.31.4

### PR DESCRIPTION
**Pull request by bin101**
fixes #1695.

I have already tested this with 2 different Gitlab services configured and also made sure that the default Github/Gitlab services still work.

### CODE REVIEW

File: pkg/commands/hosting_service/hosting_service.go [hunk 1]
```diff
@@ -80,9 +80,7 @@ func (self *HostingServiceMgr) getServiceDomain(repoURL string) (*ServiceDomain,
 	candidateServiceDomains := self.getCandidateServiceDomains()
 
 	for _, serviceDomain := range candidateServiceDomains {
-		// I feel like it makes more sense to see if the repo url contains the service domain's git domain,
```
Comment (jesseduffield) [inline pkg/commands/hosting_service/hosting_service.go:83]: so my premonition proved correct haha

**Comment by jesseduffield** [comment]
LGTM. Running the tests now

**Comment by bin101** [comment]
@jesseduffield I think this is ready to be merged ;)

**Comment by jesseduffield** [comment]
merged. Thanks for making this @bin101 !
