### PR TITLE
Fix container detection

### LINKED ISSUE #2757: When trying to open a pull request it seems lazy git needs xdg-open package which isn't safe
**Describe the bug**
When trying to open a pull request it seems lazy git needs xdg-open package if you view the unbuntu docs [here](https://manpages.ubuntu.com/manpages/focal/man1/xdg-open.1.html#:~:text=xdg%2Dopen%20opens%20a%20file,ftp%2C%20http%20and%20https%20URLs.) it says: *xdg-open is for use inside a desktop session only. It is __not__ recommended to use xdg-open as root.* I feel like I would need to install this package as root to use with WSL Unbuntu. Isn't this dangerous? If not can someone tell me how I should go about installing this package for lazygit.

**To Reproduce**

1. open lazygit on a wsl Unbuntu neovim project 
2. go to branch and click o
3.  see error message requiring xdg-open

**Expected behavior**
A pull request to be open without error

**Version**
commit=5149b24ab3dfad3860e2300519c7c583dcc8c9ff, 
build date=2023-05-03T08:00:22Z, 
build source=binaryRelease, version=0.38.2, 
os=linux, arch=amd64, 
git version=2.34.1

**Additional context**
to do a pull request from the cli I am using wslview which comes with the wslu package. Can I use this instead?

### PR DESCRIPTION
**Pull request by aritmos**
- **PR Description**

Running WSL without a container would be treated as native linux, causing problems at it would then attempt to use `xdg-open`. This was caused by `isContainer()` always returning true due to some dubious conditionals. These have been removed.

The env-var check seems to not be used by lazygit, nor any common containers, and therefore appears to only exist to manually tell lazygit to behave as if it were inside of a container. This functionality has been kept, but the env-var has been changed to be all uppercaps as to comply with the POSIX standard.

Fixes #2757
Bug introduced in 4d78d76

- **Please check if the PR fulfills these requirements**

* [x] Cheatsheets are up-to-date (run `go generate ./...`)
* [x] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [ ] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [x] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [x] Docs (specifically `docs/Config.md`) have been updated if necessary
* [x] You've read through your own file changes for silly mistakes etc

### CODE REVIEW

File: pkg/config/config_linux.go [hunk 1]
```diff
@@ -15,9 +15,7 @@ func isContainer() bool {
 
 	if strings.Contains(string(data), "docker") ||
 		strings.Contains(string(data), "/lxc/") ||
-		[]string{string(data)}[0] != "systemd" &&
-			[]string{string(data)}[0] != "init" ||
-		os.Getenv("container") != "" {
+		os.Getenv("CONTAINER") != "" {
```
Comment (stefanhaller) [inline pkg/config/config_linux.go:18]: Your change is certainly an improvement, but I find this condition still strange for two reasons: it checks the error only after looking for the strings (which is probably fine in practice, as `data` is likely to be empty when there was an error, but it's still weird), and then the funny `&& true` at the end.

I'd clean it up a bit further to something like
```go
	return err == nil && (strings.Contains(string(data), "docker") ||
		strings.Contains(string(data), "/lxc/") ||
		os.Getenv("CONTAINER") != "")
```

**Review by stefanhaller — COMMENTED** [review]
Nice, thanks for fixing this. One small suggestion for further improvement below.

**Comment by aritmos** [comment]
Noted. I want to take a bit of time ensuring this is the best way to check for containerisation, as certain discussions indicate this approach may not work correctly in some scenarios. It appears that different containers generally require separate checks, (or that unified validation is overtly complex).

Is it ok for the feature to only check for Docker and lxc as it currently does? Or are there other containers that we should strive to include?

**Comment by stefanhaller** [comment]
I'm the wrong one to answer this, as I don't use containers at all and have little experience with them. But I also saw those discussions that you are referring to when I did a very cursory stack overflow search.

But my gut feeling is that I wouldn't go too far with trying to make it perfect. Your change is an improvement in that it didn't work at all before, and now it does seem to; my recommendation would be to go with this for now and see if people still have issues.

**Comment by aritmos** [comment]
> But my gut feeling is that I wouldn't go too far with trying to make it perfect. Your change is an improvement in that it didn't work at all before, and now it does seem to; my recommendation would be to go with this for now and see if people still have issues.

Very well, thanks for the feedback. All done on my end.

File: pkg/config/config_linux.go [hunk 2]
```diff
@@ -12,16 +12,9 @@ func isWSL() bool {
...
+	return err == nil && strings.Contains(string(data), "docker") ||
 		strings.Contains(string(data), "/lxc/") ||
-		[]string{string(data)}[0] != "systemd" &&
-			[]string{string(data)}[0] != "init" ||
-		os.Getenv("container") != "" {
-		return err == nil && true
-	}
-
-	return err == nil && false
+		os.Getenv("CONTAINER") != ""
```
Comment (stefanhaller) [inline pkg/config/config_linux.go:17]: That's not quite right. `&&` binds stronger than `||`, so you do need the `()` around the `||` parts of the condition. See my example above.

Comment (aritmos) [reply pkg/config/config_linux.go]: Slipped past me, thanks for catching this!
