### PR TITLE
Fix duplicate keybinding suggestions in status bar after switching repos

### LINKED ISSUE #3612: Duplicate entries in the footer
**Describe the bug**
The footer has duplicated entries, see screenshot below.
This bug happens in all the panels

**To Reproduce**

1. Open lazygit
2. See duplicate entries

**Expected behavior**
No duplicate entries

**Screenshots**
Screenshot 2024-05-29 at 15 36 14

**Version info:**
lazygit version
```
commit=3675570a391b1a49ddd198b4c7e71e17701d4404, build date=2024-03-23T09:09:11Z, build source=binaryRelease, version=0.41.0, os=darwin, arch=arm64, git version=2.39.3 (Apple Git-146)
```
git version
```
git version 2.39.3 (Apple Git-146)
```

### PR DESCRIPTION
**Pull request by stefanhaller**
- **PR Description**

When switching to a repo that was open before, all keybinding suggestions in the status bar would show twice.

Fixes #3612.

- **Please check if the PR fulfills these requirements**

* [x] Cheatsheets are up-to-date (run `go generate ./...`)
* [x] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [x] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [ ] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [ ] Docs have been updated if necessary
* [x] You've read through your own file changes for silly mistakes etc

### CODE REVIEW

File: pkg/integration/tests/ui/keybinding_suggestions_when_switching_repos.go [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+				Lines(
+					Contains(repo).IsSelected(),
+					Contains("Cancel"),
+				).Confirm()
+			t.Views().Status().Content(Contains(repo + " → master"))
+		}
+
+		t.Views().Files().Focus()
+		t.Views().Options().Content(
+			Equals("Commit: c | Stash: s | Reset: D | Keybindings: ? | Cancel: <esc>"))
```
Comment (stefanhaller) [inline pkg/integration/tests/ui/keybinding_suggestions_when_switching_repos.go:34]: It's a little awkward that we depend on the concrete keybinding suggestions here, so we'll have to adapt the test when those change. It doesn't bother me too much though, it's still better than not having a test at all.

I did choose the panel that has the lowest number of keybindings.

**Review by jesseduffield — APPROVED** [review]
nice one
