### PR TITLE
Fix #890

### LINKED ISSUE #890: Commit command failure on v0.20.6
**Describe the bug**
Committing from lazygit no longer works with latest release.

**To Reproduce**

1. Commit from lazy git

I think this is an issue with quoting ` bash -c "git commit -m 'test'"` works if run in shell but  `bash -c git commit -m 'test'` does not

**Expected behavior**

Same as running `git commit` in shell

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: OS X
 - Lazygit Version `commit=fe6d8d62c5c0ef302ae44f95cd13a03600477199, build date=2020-07-12T13:01:48Z, build source=binaryRelease, version=0.20.6, os=darwin, arch=amd64`

**Additional context**

### PR DESCRIPTION
**Pull request by Randshot**
This PR fixes #890 by adding quotes around **non-windows** systems.
For some reason, Windows (`cmd /c`) doesn't seem to like the escaped quotes, so the git command is only quoted on **non-windows** systems.

### CODE REVIEW

File: pkg/commands/git.go [hunk 1]
```diff
@@ -470,7 +478,15 @@ func (c *GitCommand) GetHeadCommitMessage() (string, error) {
 func (c *GitCommand) AmendHead() (*exec.Cmd, error) {
 	command := "git commit --amend --no-edit --allow-empty"
 	if c.usingGpg() {
-		return c.OSCommand.ExecutableFromString(fmt.Sprintf("%s %s %s", c.OSCommand.Platform.shell, c.OSCommand.Platform.shellArg, command)), nil
+		quotedCommand := ""
```
Comment (jesseduffield) [inline pkg/commands/git.go:481]: given there's quite a bit of duplicated code here now, could you factor out the two chunks of code into a single function? I.e. everything inside the if condition. We could call it something like 'runCommandInShell' and put it in `os.go`. What are your thoughts?

Comment (Randshot) [reply pkg/commands/git.go:481]: Sure, I can factor it out into `RunCommandInShell`, below `ExecutableFromString`.

Comment (Randshot) [reply pkg/commands/git.go:481]: Instead of `RunCommandInShell`, how about `ShellCommandFromString`, or something similar, since we aren't actually running the command.

Comment (jesseduffield) [reply pkg/commands/git.go:481]: yep that works for me

**Comment by jesseduffield** [comment]
tested on mac: works fine! LGTM
