### PR TITLE
fix: escape quote character on Linux

### LINKED ISSUE #269: Starting quote has no ending quote
**Describe the bug**

When you want to commit and you have an uneven number of quotes (") in your commit message lazygit panics with the message `Starting quote has no ending quote`.

**To Reproduce**

Try to commit with a message like `a"` in laygit

**Expected behavior**

Create a commit with the subject `a"` sd;lfj 1

**Screenshots**

```
panic: Starting quote has no ending quote.

goroutine 1 [running]:
github.com/jesseduffield/lazygit/vendor/github.com/mgutz/str.ToArgv(0xc4204aa080, 0x12, 0x1, 0x1, 0xc42001ead0)
        /build/lazygit-f3gtkp/lazygit-0.0~git20180905.291.ce95e67/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/vendor/github.com/mgutz/str/funcsPZ.go:377 +0x66b
github.com/jesseduffield/lazygit/pkg/commands.(*OSCommand).RunCommandWithOutput(0xc420248600, 0xc4204aa080, 0x12, 0x0, 0x0, 0xe01fe0, 0xc42001eac0)
        /build/lazygit-f3gtkp/lazygit-0.0~git20180905.291.ce95e67/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/pkg/commands/os.go:52 +0x127
github.com/jesseduffield/lazygit/pkg/commands.(*OSCommand).RunCommand(0xc420248600, 0xc4204aa080, 0x12, 0xc4204a80a8, 0x4)
        /build/lazygit-f3gtkp/lazygit-0.0~git20180905.291.ce95e67/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/pkg/commands/os.go:61 +0x3f
github.com/jesseduffield/lazygit/pkg/commands.(*GitCommand).Commit(0xc4202b9860, 0xc420348000, 0xc4204a80a2, 0x2, 0x2, 0x2, 0x0)
        /build/lazygit-f3gtkp/lazygit-0.0~git20180905.291.ce95e67/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/pkg/commands/git.go:303 +0x1a4
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handleCommitConfirm(0xc4202a2480, 0xc420348000, 0xc42037af00, 0x0, 0xc42027bd38)
        /build/lazygit-f3gtkp/lazygit-0.0~git20180905.291.ce95e67/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/pkg/gui/commit_message_panel.go:15 +0x63
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).(github.com/jesseduffield/lazygit/pkg/gui.handleCommitConfirm)-fm(0xc420348000, 0xc42037af00, 0xc42027bd38, 0xc42034a000)
        /build/lazygit-f3gtkp/lazygit-0.0~git20180905.291.ce95e67/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/pkg/gui/keybindings.go:71 +0x3e
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybinding(0xc420348000, 0xc42037af00, 0xc4202d0c30, 0xc420000201, 0xc42027bd38, 0xc42027bd38)
        /build/lazygit-f3gtkp/lazygit-0.0~git20180905.291.ce95e67/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:703 +0x3e
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc420348000, 0xc42037af00, 0xc42027bca0, 0x6d6ebd, 0x0, 0x0)
        /build/lazygit-f3gtkp/lazygit-0.0~git20180905.291.ce95e67/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:689 +0x10b
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).onKey(0xc420348000, 0xc420509ca0, 0xc4202fc050, 0xc42035e0b0)
        /build/lazygit-f3gtkp/lazygit-0.0~git20180905.291.ce95e67/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:650 +0x1b3
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).handleEvent(0xc420348000, 0xc42027bca0, 0xc42027bc98, 0x0)
        /build/lazygit-f3gtkp/lazygit-0.0~git20180905.291.ce95e67/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:431 +0x40
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc420348000, 0xc420348000, 0x0)
        /build/lazygit-f3gtkp/lazygit-0.0~git20180905.291.ce95e67/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:391 +0x2e4
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc4202a2480, 0x0, 0x0)
        /build/lazygit-f3gtkp/lazygit-0.0~git20180905.291.ce95e67/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:382 +0x2cb
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc4202a2480)
        /build/lazygit-f3gtkp/lazygit-0.0~git20180905.291.ce95e67/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:391 +0x2f
main.main()
        /build/lazygit-f3gtkp/lazygit-0.0~git20180905.291.ce95e67/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/main.go:52 +0x13c
```

**Desktop (please complete the following information):**
 - OS: Linux neon.kde.org
 - Lazygit Version commit=ce95e67, build date=2018-09-06, build source=unknown, version=, os=linux, arch=amd64

### PR DESCRIPTION
**Pull request by sascha-andres**
Co-authored-by: Dawid Dziurla <dawidd0811@gmail.com>

Closes #269

### CODE REVIEW

File: pkg/commands/os.go [hunk 1]
```diff
@@ -139,7 +140,15 @@ func (c *OSCommand) PrepareSubProcess(cmdName string, commandArgs ...string) *ex
 
 // Quote wraps a message in platform-specific quotation marks
 func (c *OSCommand) Quote(message string) string {
+	fmt.Println(c.Platform.os)
```
Comment (jesseduffield) [inline pkg/commands/os.go]: if you want to log this you'll need to use c.Log(...)

**Comment by sascha-andres** [comment]
@jesseduffield removed, had no intention to log. Introduced as a helper for my brain I just committed while I should have removed it.

Pushed a commit removing the call

File: pkg/commands/os.go [hunk 2]
```diff
@@ -139,7 +140,15 @@ func (c *OSCommand) PrepareSubProcess(cmdName string, commandArgs ...string) *ex
...
 	message = strings.Replace(message, "`", "\\`", -1)
+	if c.Platform.os == "linux" {
+		if strings.ContainsRune(message, '\'') {
+			c.Platform.escapedQuote = `"`
```
Comment (jesseduffield) [inline pkg/commands/os.go]: I don't think we should be changing c.Platform at runtime. The idea with that is to set up platform-specific constants at compile time and then testing will be easier because we will know what their values are.

Could we perhaps make this code non-platform specific by saying something like:
```
escapedQuote := c.Platform.escapedQuote
if strings.Contains(message, c.Platform.escapedQuote) {
  escapedQuote = c.Platform.fallbackEscapedQuote
}
return escapedQuote + message + escapedQuote
```
and then add a fallbackEscapedQuote value to the platform files

Comment (sascha-andres) [reply pkg/commands/os.go]: Pushed a commit which is working and addresses your comments

**Comment by sascha-andres** [comment]
@jesseduffield does the code coverage hangs or is there a limit I unintentionally triggered?

**Comment by jesseduffield** [comment]
@sascha-andres seems like it does hang. I have no idea why. Maybe it just takes a while. @antham do you know what might be going on?

**Comment by glvr182** [comment]
Maybe it is due to the review request?

**Comment by antham** [comment]
Yep it's because an error occurred in codecov ```HTTP 400 Commit sha does not match Circle build.```, you can reload the build through circle.

**Comment by sascha-andres** [comment]
@antham @jesseduffield not sure how to do this

**Comment by antham** [comment]
I was saying that to @jesseduffield, you can't. The only thing you can do is pushing a change to trigger another build.

**Comment by sascha-andres** [comment]
@jesseduffield pushed with more documentation and checks passed

**Comment by jesseduffield** [comment]
LGTM, good work :)
