### PR TITLE
Continue/abort a conflicted cherry-pick or revert

### LINKED ISSUE #1807: Continuing a revert after fixing a merge conflict does not work
When attempting to revert a commit that results in a conflict, there is no way to continue the revert after resolving the conflict (ie. `git revert --continue`):

iTerm2 2022-03-14 at 08 58 52

Given that this works in lazygit for other similar flows like rebasing, I'd expect this one to also be feasible.

### PR DESCRIPTION
**Pull request by stefanhaller**
- **PR Description**

This is part one of a four part series of PRs that improve the cherry-pick and revert experience.

With this first PR we make it possible to continue or abort a cherry-pick or revert operation, in the same way you can continue or abort a rebase or merge. Currently this is only relevant for revert, because lazygit doesn't use git cherry-pick for copying/pasting commits. This will change in a later PR in this series though, so here we are already preparing for that.

Fixes #1807

- **Please check if the PR fulfills these requirements**

* [x] Cheatsheets are up-to-date (run `go generate ./...`)
* [x] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [x] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [x] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [ ] If a new UserConfig entry was added, make sure it can be hot-reloaded (see [here](https://github.com/jesseduffield/lazygit/blob/master/docs/dev/Codebase_Guide.md#using-userconfig))
* [ ] Docs have been updated if necessary
* [x] You've read through your own file changes for silly mistakes etc

### CODE REVIEW

File: pkg/commands/types/enums/enums.go [hunk 1]
```diff
@@ -1,22 +1,106 @@
...
-	// this means we're neither rebasing nor merging
-	REBASE_MODE_NONE RebaseMode = iota
-	// this means normal rebase as opposed to interactive rebase
-	REBASE_MODE_NORMAL
-	REBASE_MODE_INTERACTIVE
-	// REBASE_MODE_REBASING is a general state that captures both REBASE_MODE_NORMAL and REBASE_MODE_INTERACTIVE
-	REBASE_MODE_REBASING
-	REBASE_MODE_MERGING
+	// this means we're neither rebasing nor merging, cherry-picking, or reverting
+	WORKING_TREE_STATE_NONE     WorkingTreeState = 0
```
Comment (jesseduffield) [inline pkg/commands/types/enums/enums.go:10]: I don't like how we're using the same type (`WorkingTreeState`) for the bits as for the bitfield. Naively I would expect that I could directly check `if workingTreeState == WORKING_TREE_STATE_CHERRY_PICKING` but that's really only going to return true if we're only cherry picking and not also merging. I also can't do `if workingTreeState == WORKING_TREE_STATE_CHERRY_PICKING || workingTreeState == WORKING_TREE_STATE_REBASING` to ask if it's either cherry picking or rebasing.

So I'm wondering, how about we just have a struct of booleans:
```go
type WorkingTreeState struct {
  rebasing bool
  merging bool
  cherryPicking bool
  reverting bool
}
```

And then define methods on that struct.

**Review by jesseduffield — CHANGES_REQUESTED** [review]
Nice work. One thing

File: pkg/commands/types/enums/enums.go (hunk 1 above)
Comment (stefanhaller) [reply pkg/commands/types/enums/enums.go]: Good point. Yes, a struct is an improvement to this.

I couldn't do this as a fixup, so I rebased and force-pushed. I added dceb1960f026 as a preparation, and then d2573dc5dc93 is the changed commit. The rest of the branch is unchanged except for adaptions to the new API.

**Review by jesseduffield — APPROVED** [review]
LGTM
