### PR TITLE
Fix pasting multi-line text into commit message panel

### LINKED ISSUE #3151: Pasting multiple lines into commit summary field executes commands
**Describe the bug**
When pasting multiple lines into commit summary field, any characters on lines after the first line will be executed as commands.

**To Reproduce**

1. Stage a change.
2. Open the commit form (`c`).
3. Paste this into the commit summary field:
   ```
   B
   o
   ```

**Expected behavior**
Only the first line is used. Subsequent lines are discarded.

OR

Subsequent lines are pasted into the commit description field.

**Screenshots**

https://github.com/jesseduffield/lazygit/assets/921609/f8624dba-8b6e-41f3-94bf-61a93dc0abd9

**Version info:**
`lazygit --version`: 0.40.2
`git --version`: 2.42.0

**Additional context**
This happens to me frequently when I paste the contents of the "copy commit message" shortcut. In this example it's just opening a file (`o`), but in some cases it can cause much more harm.

### LINKED ISSUE #4066: Paste multiline commit message in reword is dangerous
**Describe the bug**
I had a prewritten commit message that I wanted to update an existing commit. I launched lazygit and used the reword command, and assumed/hoped it would correctly handle a multiline paste and put the first line in the title, and the remaining lines in the description. Ie, so the result would be identical to if this multiline string was originally placed in the commit message.

Instead, lazygit used the first line as the commit title, and started interpreting the remaining lines as lazygit keyboard actions, which could potentially have very serious implications for the state of my local repository. 

**To Reproduce**

1. Copy a multiline commit message from any text buffer/editor.
2. Open lazygit and select a commit and press 'r' for reword action
3. Paste the string into the reword form

**Expected behavior**
First line in the message title
Remaining lines in the description

**Screenshots**

**Version info:**
```
[14:03:49] ❯ lazygit --version
commit=, build date=, build source=homebrew, version=0.44.1, os=darwin, arch=arm64, git version=2.47.0
[14:03:55] ❯ git --version
git version 2.47.0
```

**Additional context**

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.

### LINKED ISSUE #4216: Freezes when pasting a string that includes a line breaks
**Describe the bug**

In Commit message mode,
Pasting text with multiple line breaks causes the lazygit to freeze.
There seems to be no solution other than quitting the terminal emulator.

**To Reproduce**

1. Open lazygit
2. Input 'c' to go commit mode
3. Paste with `ctrl` + `shift` + `v`
4. Pasting only gets to the middle of the first line and then stops
5. Shell freezes

OK sample

```text
fix(heirline): unify background color scheme

```

NG sample

```text
fix(heirline): unify background color scheme

Updated background color assignments in the heirline configuration to use
`scheme.bg` instead of local scheme values. This change ensures a consistent
background color across different UI elements.
```

**Expected behavior**

If there are two line breaks at the end of the first line,
it has the same effect as tab and the remaining text is pasted into the commit description.

**Tried**

I tried it in the following environment, but the symptoms are the same:

- Powershell7 in WezTerm
- Powershell7 in Windows Terminal
- Powershell7 in Alacritty
- cmd.exe in Windows Terminal

**Version info:**

lazygit 

```text
commit=c03b89227092b852d50015d289a7c6d8c69811c5, build date=2025-01-17T13:37:10Z, build source=binaryRelease, version=0.45.2, os=windows, arch=amd64, git version=2.42.0.windows.1
```

git 

```text
git version 2.42.0.windows.1
```

**Additional context**

config https://github.com/ShortArrow/dotfiles/blob/develop/lazygit/config.yaml

logs

```text
Jan 27 09:16:45 |INFO| git rev-parse --symbolic-full-name main@{u} (161.9271ms)
Jan 27 09:16:45 |DEBU| RunCommand command="git -C C:/Users/shoutarou_t/Documents/GitHub/dotfiles rev-parse --path-format=absolute --absolute-git-dir"
Jan 27 09:16:46 |INFO| postRefreshUpdate for tags took 0s
Jan 27 09:16:46 |INFO| git rev-parse --abbrev-ref --verify
HEAD (78.9773ms)
Jan 27 09:16:46 |INFO| git for-each-ref --sort=refname --format=%(refname:short) refs/remotes (79.8178ms)
Jan 27 09:16:46 |INFO| postRefreshUpdate for remotes took 0s
Jan 27 09:16:46 |INFO| postRefreshUpdate for remoteBranches took 0s
Jan 27 09:16:46 |INFO| git -c log.showSignature=false log -g --abbrev=40 --format=%h%x00%ct%x00%gs%x00%p (89.8188ms)
Jan 27 09:16:46 |INFO| postRefreshUpdate for reflogCommits
took 0s
Jan 27 09:16:46 |DEBU| RunCommand command="git merge-base HEAD refs/remotes/origin/main"
Jan 27 09:16:46 |DEBU| RunCommand command="git merge-base develop develop@{u}"
Jan 27 09:16:46 |DEBU| RunCommand command="git for-each-ref --sort=-committerdate --format=%(HEAD)%00%(refname:short)%00%(upstream:short)%00%(upstream:track)%00%(push:track)%00%(subject)%00%(objectname)%00%(committerdate:unix) refs/heads"
Jan 27 09:16:46 |INFO| git merge-base develop develop@{u} (101.7162ms)
Jan 27 09:16:46 |INFO| git for-each-ref --sort=-committerdate --format=%(HEAD)%00%(refname:short)%00%(upstream:short)%00%(upstream:track)%00%(push:track)%00%(subject)%00%(objectname)%00%(committerdate:unix) refs/heads (100.1921ms)
Jan 27 09:16:46 |INFO| postRefreshUpdate for localBranches
took 21.8µs
Jan 27 09:16:46 |INFO| git merge-base HEAD refs/remotes/origin/main (135.4556ms)
Jan 27 09:16:46 |INFO| git log HEAD --topo-order --oneline
--pretty=format:%H%x00%at%x00%aN%x00%ae%x00%D%x00%p%x00%m%x00%s --abbrev=40 -300 --no-show-signature -- (148.0885ms)
Jan 27 09:16:46 |DEBU| using cache for key rebase.updateRefs
Jan 27 09:16:46 |INFO| postRefreshUpdate for commits took 10.003ms
Jan 27 09:16:46 |DEBU| using cache for key rebase.updateRefs
Jan 27 09:16:55 |INFO| Heap memory in use: 3.6 MB
Jan 27 09:16:55 |INFO| refreshing the following scopes in sync mode: files
Jan 27 09:16:55 |INFO| refreshed merge conflicts in 0s
Jan 27 09:16:55 |DEBU| using cache for key status.showUntrackedFiles
Jan 27 09:16:55 |DEBU| RunCommand command="git status --untracked-files=all --porcelain -z --find-renames=50%"
Jan 27 09:16:55 |INFO| git status --untracked-files=all --porcelain -z --find-renames=50% (75.4137ms)
Jan 27 09:16:55 |INFO| refreshed files in 83.1826ms
Jan 27 09:16:55 |INFO| Refresh took 83.281ms
Jan 27 09:17:05 |INFO| Heap memory in use: 3.7 MB
Jan 27 09:17:05 |INFO| refreshing the following scopes in sync mode: files
Jan 27 09:17:05 |INFO| refreshed merge conflicts in 0s
Jan 27 09:17:05 |DEBU| using cache for key status.showUntrackedFiles
Jan 27 09:17:05 |DEBU| RunCommand command="git status --untracked-files=all --porcelain -z --find-renames=50%"
Jan 27 09:17:05 |INFO| git status --untracked-files=all --porcelain -z --find-renames=50% (69.4437ms)
Jan 27 09:17:05 |INFO| refreshed files in 80.6637ms
Jan 27 09:17:05 |INFO| Refresh took 80.6637ms
Jan 27 09:17:15 |INFO| refreshing the following scopes in sync mode: files
Jan 27 09:17:15 |INFO| Heap memory in use: 3.9 MB
Jan 27 09:17:15 |INFO| refreshed merge conflicts in 514.1µs

Jan 27 09:17:15 |DEBU| using cache for key status.showUntrackedFiles
Jan 27 09:17:15 |DEBU| RunCommand command="git status --untracked-files=all --porcelain -z --find-renames=50%"
Jan 27 09:17:15 |INFO| git status --untracked-files=all --porcelain -z --find-renames=50% (74.0176ms)
```

### PR DESCRIPTION
**Pull request by stefanhaller**
- **PR Description**

When pasting a multi-line commit message into the subject field of the commit editor, we would interpret the first newline as the confirmation for closing the editor, and then all remaining characters as whatever command they are bound to, resulting in executing all sorts of arbitrary commands.

Now we recognize this being a paste, and interpret the first newline as moving to the description.

Also, prevent tabs in the pasted content from switching to the respective other panel; simply insert four spaces instead, which should be good enough for the leading indentation in pasted code snippets, for example.

Finally, disable pasting text into non-editable views; my assumption is that this is always a mistake, as it would execute arbitrary commands depending on what's in the clipboard.

This depends on the terminal emulator supporting bracketed paste; I didn't find one on Mac that doesn't (I tested with Terminal.app, iTerm2, Ghostty, kitty, Alacritty, WezTerm, and VSCode's builtin terminal. It works well in all of them).

I couldn't get it to work in Windows Terminal though, and I don't understand why, as it does seem to support bracketed paste (it works in bash).

Fixes #3151
Fixes #4066
Fixes #4216

- **Please check if the PR fulfills these requirements**

* [x] Cheatsheets are up-to-date (run `go generate ./...`)
* [x] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [ ] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [ ] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [ ] If a new UserConfig entry was added, make sure it can be hot-reloaded (see [here](https://github.com/jesseduffield/lazygit/blob/master/docs/dev/Codebase_Guide.md#using-userconfig))
* [ ] Docs have been updated if necessary
* [x] You've read through your own file changes for silly mistakes etc

### CODE REVIEW

File: pkg/gui/controllers/commit_description_controller.go [hunk 1]
```diff
@@ -75,6 +75,22 @@ func (self *CommitDescriptionController) switchToCommitMessage() error {
 	return nil
 }
 
+func (self *CommitDescriptionController) handleTogglePanel() error {
```
Comment (jesseduffield) [inline pkg/gui/controllers/commit_description_controller.go:78]: Something that is not clear here is that `opts.Config.Universal.TogglePanel` defaults to `tab`. So a reader could get confused as to why we're conditionally inserting spaces. A comment should clear up that confusion.

Things probably get awkward when a user remaps these keys, and I'm not sure of a good way of dealing with that (doesn't need to be solved in this PR)

File: vendor/github.com/jesseduffield/gocui/gui.go [hunk 2]
```diff
@@ -1311,6 +1311,10 @@ func (g *Gui) onKey(ev *GocuiEvent) error {
 	switch ev.Type {
 	case eventKey:
 
+		if g.IsPasting && ev.Key == KeyCtrlJ {
```
Comment (jesseduffield) [inline vendor/github.com/jesseduffield/gocui/gui.go:1314]: This deserves a code comment explaining what we're doing. Even reading the commit message, it's not actually clear to me how KeyCtrlJ and KeyCtrlM relate to \n and \r.

File: vendor/github.com/jesseduffield/gocui/tcell_driver.go [hunk 3]
```diff
@@ -417,6 +420,11 @@ func (g *Gui) pollEvent() GocuiEvent {
 			Type:    eventFocus,
 			Focused: tev.Focused,
 		}
+	case *tcell.EventPaste:
+		return GocuiEvent{
+			Type:  eventPaste,
+			Start: tev.Start(),
```
Comment (jesseduffield) [inline vendor/github.com/jesseduffield/gocui/tcell_driver.go:426]: Is the idea that there's two paste events: one for starting the paste and one for finishing the paste, and if it's the first kind then Start will be true? If so it would be good to add a comment to that affect against the GocuiEvent struct

File: pkg/gui/controllers/commit_message_controller.go [hunk 4]
```diff
@@ -140,6 +156,10 @@ func (self *CommitMessageController) setCommitMessageAtIndex(index int) (bool, e
 }
 
 func (self *CommitMessageController) confirm() error {
+	if self.c.GocuiGui().IsPasting {
```
Comment (jesseduffield) [inline pkg/gui/controllers/commit_message_controller.go:159]: I'd spell this out in a comment too i.e. the default keybinding for confirm is enter, and newlines are interpreted as enter presses when pasting.

**Review by jesseduffield — CHANGES_REQUESTED** [review]
Nice work, see comments

File: pkg/gui/controllers/commit_description_controller.go (hunk 1 above)
Comment (stefanhaller) [reply pkg/gui/controllers/commit_description_controller.go:78]: Ah interesting, I hadn't considered remapping keys at all. I added a condition and a comment in 8256ed219e7a, please have a look.

File: pkg/gui/controllers/commit_message_controller.go (hunk 4 above)
Comment (stefanhaller) [reply pkg/gui/controllers/commit_message_controller.go]: Added a condition and a comment in 8256ed219e7a, like for the other handlers.

File: vendor/github.com/jesseduffield/gocui/gui.go (hunk 2 above)
Comment (stefanhaller) [reply vendor/github.com/jesseduffield/gocui/gui.go:1324]: Added a comment in 0c0287c8cf17, does this help? It's still slightly mysterious to me, I tried to be honest about this in the comment.

File: vendor/github.com/jesseduffield/gocui/tcell_driver.go (hunk 3 above)
Comment (stefanhaller) [reply vendor/github.com/jesseduffield/gocui/tcell_driver.go:427]: Yes, that's true. I added a comment in 76924d8982fa, is that enough? Feel free to push fixups if you want to further improve it.

**Review by jesseduffield — APPROVED** [review]
LGTM, great work on those comments
