### PR TITLE
Re-apply filter when model changes

### LINKED ISSUE #2816: Filtered view doesn't update when underlying model changes
It seems that the filtered view remembers indices into the model of the items that it should display. If the model changes, these are not updated, so the wrong items are shown.

There are probably many variations of situations in which this happens, but the two most common ones that I have run into are:

### Checking out a filtered branch
1. Press `/` and filter the list of branches down so that only a single branch is shown (which is not the current one)
2. Press space to check out this branch
3. Expected: the same branch should still be displayed in the filtered list; actual: an arbitrary different one is displayed instead

### Deleting a filtered branch
1. Filter the list of branches down so that three branches are shown
2. Select one of these and press `d` to delete it
3. Expected: only two branches should be displayed now; actual: it still shows three branches, and (depending on the order of the branches) totally arbitrary ones

**Version info:**
commit=a30537a4da5e6633135f9a7f423a5b23b14d9797, build date=2023-07-21T15:58:51Z, build source=unknown, version=a30537a4, os=darwin, arch=arm64, git version=2.41.0.49.g2c35e38aee

### PR DESCRIPTION
**Pull request by stefanhaller**
- **PR Description**

Fixes #2816 and #3056.

### CODE REVIEW

File: pkg/gui/controllers/helpers/search_helper.go [hunk 1]
```diff
@@ -227,6 +227,18 @@ func (self *SearchHelper) OnPromptContentChanged(searchString string) {
...
 }
 
+func (self *SearchHelper) ReApplyFilter(context types.Context) {
+	state := self.searchState()
+	if context == state.Context {
+		filterableContext, ok := context.(types.IFilterableContext)
+		if ok {
+			filterableContext.SetSelectedLineIdx(0)
+			_ = filterableContext.GetView().SetOriginY(0)
+			filterableContext.ReApplyFilter()
```
Comment (AzraelSec) [inline pkg/gui/controllers/helpers/search_helper.go:237]: If we rename the `ReApplyFilter` method on the `IFilterableContext`, it would probably make sense to move all this logic inside it. Also, would it make sense, in your opinion, to reset the filter in case of an empty resulting list? I'm not sure, but it's an option.

**Review by AzraelSec — COMMENTED** [review]
@stefanhaller, thank you for the PR - I was trying to figure out how to proceed, but I was unsure. I've left a couple of comments to propose a change, but I can confirm that this patch definitely fixes the issues!

File: pkg/gui/controllers/helpers/search_helper.go (hunk 1 above)
Comment (jesseduffield) [reply pkg/gui/controllers/helpers/search_helper.go:237]: I would not reset the filter because there may intermittently be an empty resulting list (I'm thinking of the weirdness that happens when refreshing the files view for example)

**Comment by jesseduffield** [comment]
I'm happy with this approach. I considered instead moving the logic inside the PostRefreshUpdate method but figured it really is only within the refresh helper that we want to be updating the filter.

File: pkg/gui/controllers/helpers/search_helper.go (hunk 1 above)
Comment (stefanhaller) [reply pkg/gui/controllers/helpers/search_helper.go:237]: The files view is not filterable (yet?), so this wouldn't be an issue right now. But I agree, the behavior could be strange in other cases; say you filter the branches list, type so much that no branch shows up, and then the background fetch comes along and refreshes the branches.

**Comment by stefanhaller** [comment]
> I considered instead moving the logic inside the PostRefreshUpdate method but figured it really is only within the refresh helper that we want to be updating the filter.

Yes, I had the same thoughts. 😄

File: pkg/gui/context/filtered_list.go [hunk 2]
```diff
@@ -41,6 +41,10 @@ func (self *FilteredList[T]) ClearFilter() {
 	self.SetFilter("")
 }
 
+func (self *FilteredList[T]) ReApplyFilter() {
```
[the remark this answers is not in the document]
Comment (stefanhaller) [reply pkg/gui/context/filtered_list.go:44]: Exposing `applyFilter` publicly would be fine with me (I'd rename it to ReApplyFilter then), but on the other hand the one-line forwarder doesn't bother me much. So no strong opinion here.

I wouldn't rename it to `InvalidateModel` though, this would sound misleading to me. Maybe `OnModelInvalidated`, but I'm not sure why that's better.

The other question is more interesting: should we move some of the logic specific to contexts (e.g. selecting lines etc) from SearchHelper to FilteredListViewModel. The same could be asked for the existing code in `OnPromptContentChanged`. I don't really have much of an opinion here, happy to follow whatever Jesse tells me to do. Personally I'd leave everything the way it is, as that's the least amount of work. 😄

[the remark this answers is not in the document]
Comment (jesseduffield) [reply pkg/gui/context/filtered_list.go:44]: Happy to leave things where they are for now, but happy to accept a separate PR that does the refactor if anybody's up to it

**Review by jesseduffield — APPROVED** [review]
LGTM, great work
